### PR TITLE
fix wasm and nostd builds

### LINKED ISSUE #861: CI check for wasm isn't working
Building async-std for the wasm target is completely broken at the moment:

- https://github.com/async-rs/async-std/issues/851
- https://github.com/async-rs/async-std/issues/843

The reason why it hasn't been detected is that the CI of async-std for wasm isn't working. [Here](https://github.com/async-rs/async-std/runs/1003328709#step:9:1)'s an example.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #861,#843

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@jbr @yoshuawuyts any ideas about the CI issues, they are quite odd. Suddenly there are missing crates Oo, seems like a CI bug, as this works fine locally.

**Comment by jbr** [comment]
Agreed that it seems to be a CI issue, but I don't think it's related to this PR. See CI failures at https://github.com/async-rs/async-std/pull/853/checks?check_run_id=988260537

Maybe it's related to caching? Does it help to temporarily comment out L32-48 of ci.yml?

**Comment by jbr** [comment]
@dignifiedquire See the above PR for a possible long-term solution to the wasm/no-std problem, but at the cost of requiring all wasm users to enable a `wasm` feature, which would be a breaking change. I have no idea how to get both no-std and wasm compiling simultaneously without that, though, and don't understand how it ever worked

**Review by yoshuawuyts — APPROVED** [review]

**Comment by Fishrock123** [comment]
This seems fine to me, although me and @jbr were discussing with @yoshuawuyts last week and Yosh noted that just getting it to build may not be enough and actual was builds could still have issues when run in their environments.

I'm not so invested in that personally but is something that may be good to track, both for async-std and http-rs.

**Comment by dignifiedquire** [comment]
yes we need to run the tests as well, I had wasm-bindgen-test working at some point on my machine, but forgot the magical invocations..

**Pull request merged**
