### PR TITLE
update smol dependencies

### PR DESCRIPTION
**Pull request by Keruspe**
Updates all of the subcomponents of smol that we're now using to their latest versions

cc @stjepang

### CODE REVIEW

**Review by stjepang — APPROVED** [review]
Lgtm, thanks!

**Comment by stjepang** [comment]
The codebase has a dozen or so instances of this line of code:

```rust
once_cell::sync::Lazy::force(&crate::rt::RUNTIME);
```

With latest version of smol, it is not needed anywhere except in `src/task/builder.rs`. Can you delete it everywhere except in the `task` module?

This way, if libraries like `async-h1` depend on `async-std` and only use its timers, the executor threadpool will not even be initialized. The only thread that gets started is the "async-io" thread.

**Comment by Keruspe** [comment]
Nice catch indeed, fixed

**Comment by Keruspe** [comment]
Updated to newly released 1.0 versions

**Review by dignifiedquire — APPROVED** [review]
thanks

**Comment by Keruspe** [comment]
@stjepang async-executor 1.1.0 fails o android:

```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.1.0/src/lib.rs:29:47
   |
29 | use std::sync::atomic::{AtomicBool, Ordering, AtomicU64, AtomicUsize};
   |                                               ^^^^^^^^^
   |                                               |
   |                                               no `AtomicU64` in `sync::atomic`
   |                                               help: a similar name exists in the module: `AtomicU8`
```

**Comment by stjepang** [comment]
Should be fixed with async-executor v1.1.1

**Pull request merged**
