### PR TITLE
Remove `extension_trait`

### PR DESCRIPTION
**Pull request by nnethercote**
@yoshuawuyts says that the documentation generated by `extension_trait` is no longer necessary, which opens the door to removing the `extension_trait` macro. This PR does that, in a series of small steps. When combined with the improvements in #1005, the time for a full `cargo check` has reduced by about 55%, and the time for an incremental `cargo check` rebuild has reduced by about 75%.

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

cc @lqd

**Comment by nnethercote** [comment]
Oh, `src/lib.rs` has `#![recursion_limit = "2048"]`, that can probably be removed now.

**Comment by nnethercote** [comment]
> Oh, `src/lib.rs` has `#![recursion_limit = "2048"]`, that can probably be removed now.

It can, I just pushed an additional commit to remove it.

**Review by yoshuawuyts — APPROVED** [review]
Tested this locally, and woah this compiles quickly! -- incredibly excited about this. Thanks so much @nnethercote!

**Comment by lnicola** [comment]
@yoshuawuyts just curious, what's "quickly" here? I might have tested incorrectly, but `async-std` without its dependencies builds in about 2 seconds for me.

**Comment by yoshuawuyts** [comment]
@lnicola oh, I meant "quickly" compared to compile times before this change. In benchmarks this change showed a >50% improvement in compile times, and trying it locally it def felt noticeably faster!

**Pull request merged**
