### PR TITLE
feat: new channels

### PR DESCRIPTION
**Pull request by dignifiedquire**
- add new top level `channel` module
- reimplement existing channels using `async-channel`

### CODE REVIEW

**Comment by stjepang** [comment]
Looks like channel is module is in the wrong place: it's in `async_std::channel`, while it should be `async_std::sync::channel`

**Comment by yoshuawuyts** [comment]
> Looks like channel module is in the wrong place: it's in async_std::channel

@stjepang that's the intent; the libs team has been talking about possibly breaking `std::sync` up into smaller bits anyway, and we figured a `channel` impl would be a good candidate for this. But now that you know it's intentional I'm curious to hear what you think!

**Comment by stjepang** [comment]
Ha, interesting! I actually like `channel` as a top-level module and wish `std` did the same.

**Comment by dignifiedquire** [comment]
Going to close this for now. Will rework later.

**Pull request closed without merging**
