### PR TITLE
add an unstable `task::blocking` function

### LINKED ISSUE #65: Make `blocking` public?
Hi! I was using `async-std` in my [`cacache`](https://crates.io/crates/cacache) library. One of the things that I'm trying to do is implement `AsyncWrite` for it, but it turns out I'm using a tmpfile library that does sync i/o. Because of that, I pretty much copy-pasted the `AsyncWrite` impl for `async-std`'s `File`, and it turns out with the latest version, `task::blocking` is now private, so I can't just... do that. (To clarify, I was using async-std pre-release, when I needed to use async-pool for this, and I just started porting the code over tonight when I ran into this).

For the sake of compatibility, it would be nice to have this available. My code that's doing this is over here, in case there turns out to be a Better Way™ to do what I'm trying to do that hopefully doesn't involve reimplementing tmpfile logic: https://github.com/zkat/cacache-rs/blob/zkat/async/src/content/write.rs#L147-L256

Cheers!

### LINKED ISSUE #219: Set up task::Tag in blocking tasks
Blocking tasks should behave similarly to other tasks - in particular, they should be nameable, have an id, and task-locals.

### PR DESCRIPTION
**Pull request by yoshuawuyts**
This add an unstable `task::spawn_blocking` function to unblock people (lol) waiting for #65. I'm not sure if this is the right API, but we've talked about adding `spawn_local` at some point in the future too, so it doesn't seem too wrong either.

Regardless, I think it's time to provide people with at least "unstable" access to this. Thanks!

Closes #219, closes #65 

cc/ @zkat 

## Screenshot

Screenshot_2019-09-28 async_std task - Rust

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
I still think we should merge this, but I'm almost wondering if the mapping of blocking -> future shouldn't be part of the thread submodule.

There's something about blocking tasks that makes me feel like it should be part of that. Not sure tho; feel like we may need to talk it through sometime.

**Comment by skade** [comment]
I see the issue that this function will be _effectively_ stable. The proliferation of reaching for an `unstable` flag to expose things people are asking for will either force people to choose the unstable flag all the time and not caring about it and taking the ability from us to iterate on the solution.

We should instead spend more time on figuring out what a stable blocking interface should be.

**Comment by dvc94ch** [comment]
Having to make some changes after running `cargo update` is better than having to maintain a fork, that is out of date. And isn't semver supposed to alleviate this? I don't understand all this commitment to find a solution that will be supported indefinitly.

**Comment by dvc94ch** [comment]
After some reflection I see the problem. Whenever a crate exports a trait the crate can only occur once in the dependency tree.

**Comment by zkat** [comment]
Yes please! Is this moving forward? :D

**Comment by yoshuawuyts** [comment]
@skade We've been talking about this for _months_ now, and we haven't made any tangible progress on an API design. Currently there's quite a few other things in-progress, and several other things marked as priority before we could get around to designing this. Where I estimate it'll probably be at least another month or two before this can be prioritized, which imo is too long.

I think the higher order bit would be to unblock people who have been waiting on this feature for a long time already, so they can move forward and build projects on top of async-std. We can provide detailed upgrade instructions if we decide to stabilize a different version of the API.

cc/ @stjepang I'd be curious for your input here also.

**Comment by stjepang** [comment]
I'm comfortable with stabilizing this function, provided we do two changes:

1. Rename to something simpler, perhaps `task::blocking()`.
2. Return a regular `task::JoinHandle<T>` from the function.

We should probably make blocking tasks behave just like normal tasks spawned using `task::spawn()`, except `task::blocking()` would give a hint to the scheduler that this task might block. That means inside blocking tasks we should be able to use task-locals, `task::current()` and so on.

**Comment by yoshuawuyts** [comment]
@stjepang and I had a chat yesterday, and we're on the same page about what to do. I agree with what he's said in https://github.com/async-rs/async-std/pull/251#issuecomment-538843574.

**Comment by yoshuawuyts** [comment]
Alright, this PR now exposes `task::blocking`, and implements #219 as requested. This should be good to review now!

**Comment by yoshuawuyts** [comment]
I've addressed all feedback, and things are compiling + tests passing so I think this should be good to merge!

**Pull request merged**
