### PR TITLE
Unique stream extension

### PR DESCRIPTION
**Pull request by lqf96**
This pull request adds `Stream::unique` and `Stream::unique_by` extension which filters out duplicate items in the stream. These extensions are similar to [`Itertools::unique`](https://docs.rs/itertools/0.7.8/itertools/trait.Itertools.html#method.unique) and [`Itertools::unique_by`](https://docs.rs/itertools/0.7.8/itertools/trait.Itertools.html#method.unique_by) and correspond to the ReactiveX [`Distinct`](http://reactivex.io/documentation/operators/distinct.html) operator.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@lqf96 thanks heaps for this PR! Itertools has quite a few extensions beyond what std provides, and I'm a bit hesitant to start adding them. Not even [rayon has this](https://docs.rs/rayon/1.2.1/rayon/?search=unique). This *does* seem useful though; but I'm leaning towards perhaps saying that this is out of scope for `async-std`.

@stjepang do you have thoughts?

**Comment by lqf96** [comment]
Hi @yoshuawuyts, if you think this is out of scope for `async-std` then I can open a PR for `futures-rs` instead...

**Comment by yoshuawuyts** [comment]
@lqf96 yeah I think that might be better for now. Apologies!

**Comment by lqf96** [comment]
I'm closing this pull request and re-submit this to `futures-rs`.

**Pull request closed without merging**
