### PR TITLE
Implement a simple Map transformer for Stream

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Ref #129

**Comment by yoshuawuyts** [comment]
cc/ @montekki probably the methods we're missing the most right now are map/for_each and try_map/try_for_each. This PR is a bit stale, and I think we should close it. But would you be willing to implement those methods for Stream? 

Thanks heaps!

**Comment by montekki** [comment]
@yoshuawuyts ok

**Comment by montekki** [comment]
@yoshuawuyts is `try_map` a thing? Other three are ready.

**Comment by yoshuawuyts** [comment]
@montekki `try_map` isn't a thing, unfortunately. I think it's probably okay to leave it out for now.

**Pull request closed without merging**
