### PR TITLE
Add try_clone for TcpStream

### PR DESCRIPTION
**Pull request by atbentley**
From the discussion in #553 

I also updated the client/server example to use `try_clone` instead of `Arc`, as well as added a small test.

### CODE REVIEW

**Comment by atbentley** [comment]
Not sure why this is failing on windows, is anyone able to point me in a direction here?

**Comment by yoshuawuyts** [comment]
@atbentley I'm unsure, but it seems this might be an issue in `mio`:

```txt
---- cloned_streams stdout ----
thread 'cloned_streams' panicked at 'cannot register an I/O event source: Os { code: 87, kind: Other, message: "The parameter is incorrect." }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
We're not passing any extra parameters to the underlying OS primitives here; so it feels like it's coming from a lower level. This makes me wonder if going down the `Arc` route isn't the more reliable option.

**Comment by stjepang** [comment]
I believe this is the same problem as in https://github.com/tokio-rs/tokio/issues/774

**Comment by guiri14** [comment]
Definitely looking forward to this. As it stands, I don’t see any way to read a socket on one thread and write it on another on rust stable. I’ve worked around it in the meantime using Arc::get_mut_unchecked, which feels pretty gross.  It does seem to work fine, though.

**Comment by guiri14** [comment]
I attempted creating a std TcpStream, cloning it, and then using async_std::net::TcpStream's From<> impl to convert the std stream. I also received the error

```thread 'main' panicked at 'cannot register an I/O event source: Os { code: 87, kind: Other, message: "The parameter is incorrect." }', C:\Users\jfont\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.4.0\src\net\driver\mod.rs:183:20```

This happens after I've already converted the first one and I'm converting the second one. Here's the demonstration code:
```
let tcp_a = std::net::TcpStream::connect("127.0.0.1:43800")?;
let tcp_b = tcp_a.try_clone()?;
let reader = Arc::new(Mutex::new(async_std::net::TcpStream::from(tcp_a)));
let writer = Arc::new(Mutex::new(async_std::net::TcpStream::from(tcp_b)));
```

**Pull request closed without merging**
