### PR TITLE
Add Future::join and Future::try_join

### PR DESCRIPTION
**Pull request by portgasd666**
Addresses #470 .

@yoshuawuyts Regarding the module level documentation changes, is the plan to replace `join!` and `try_join!` in the documentation with `join` and `try_join` ?

### CODE REVIEW

**Comment by stjepang** [comment]
I like this change. 👍

To be honest, I don't find `join!` and `try_join!` all that useful nor expect those macros to pop up in practice. It seems a lot of people are confused by future joining in general (see [here](https://www.reddit.com/r/rust/comments/dt6u0s/joined_futures_will_run_concurrently_not_in/)).

Instead, I expect people will spawn futures to make them run in paralle/concurrently rather than joining futures.

wdyt, @yoshuawuyts?

**Comment by yoshuawuyts** [comment]
@stjepang you might be right actually. Agree we can probably remove them without much loss.

**Comment by portgasd666** [comment]
I have changed the reference to `join!` and `try_join!` in the module documentation to refer to 'join' and 'try_join` functions instead.

**Comment by stjepang** [comment]
@yoshuawuyts @portgasd666 In that case, let's also remove macros `join!` and `try_join!`? :)

**Pull request merged**
