### PR TITLE
chore: release v1.6.3

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@yoshuawuyts the errors are real, it seems that the docs macro broke :O

**Comment by dignifiedquire** [comment]
Tested and older nightlies (`2020-05-01`) compiles the docs fine. So there is either a regression or a sudden change in the compiler that breaks things

**Comment by dignifiedquire** [comment]
I suspect https://github.com/rust-lang/rust/pull/73566 to be the issue

**Comment by yoshuawuyts** [comment]
@dignifiedquire oooph ://

I've added a comment on the issue you linked so people are notified. But we should probably open a dedicated issue for it on the compiler. It's annoying we now cannot release :(

**Comment by Keruspe** [comment]
Blocking issue has been addressed in latest nightly right?

**Comment by killzoner** [comment]
Apparently yes (https://github.com/rust-lang/rust/issues/75100#issuecomment-673133934), but somehow nobody had time to rerun CI. Probably soon

**Comment by dignifiedquire** [comment]
I tried rerunning, but I don't know how to get github actions to pick up the newer nightly :/

**Comment by killzoner** [comment]
@dignifiedquire it did the trick 🎉

**Comment by dignifiedquire** [comment]
Released, finally :)

**Pull request merged**
