### PR TITLE
add io::cursor

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Adds `io::Cursor` and makes it so `io::prelude::*` behaves the way it does in std (so it can actually be implemented - though this might just have been a bug on my side??).

Ref #131. Thanks!

### CODE REVIEW

**Comment by stjepang** [comment]
Why is the `AsyncBufRead` impl commented out? Is there something we're still missing that would make it compile?

**Comment by yoshuawuyts** [comment]
@stjepang yeah, not sure -- I can't get the borrow checker to allow it. If you want to take a look that'd definitely be helpful.

2019-09-10-134945_1920x1080

**Comment by taiki-e** [comment]
@yoshuawuyts it needs to use Pin::get_mut
```rust
Poll::Ready(io::BufRead::fill_buf(&mut self.get_mut().inner))
```
https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-io/src/lib.rs#L599

**Comment by yoshuawuyts** [comment]
@taiki-e that did the trick! -- thanks so much!

**Pull request merged**
