### PR TITLE
remove custom log code in favor of macro crate

### PR DESCRIPTION
**Pull request by yoshuawuyts**
This removes our custom log macro code in favor of using [`kv-log-macro`](https://github.com/yoshuawuyts/kv-log-macro). This is a temporary crate that exists only until https://github.com/rust-lang-nursery/log/pull/353 lands which enables progress on https://github.com/rust-lang-nursery/log/issues/328. Thanks!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Also side note, I'm particularly excited for shorthand kv support as suggested [here](https://github.com/rust-lang-nursery/log/issues/343#issuecomment-524697292):

__current__
```rust
trace!("block_on", {
    parent_id: parent_id,
    child_id: child_id,
});
```

__proposed__
```rust
trace!("block_on", { parent_id, child_id });
```

**Comment by stjepang** [comment]
can you do cargo fmt and then merge?

**Pull request merged**
