### PR TITLE
Document task::spawn's support for blocking tasks.

### LINKED ISSUE #905: Docs for task::spawn must mention support for tasks that block
The async-std blog post ["stop worrying about async blocking"](https://async.rs/blog/stop-worrying-about-blocking-the-new-async-std-runtime/) explains that `spawn_blocking` is no longer needed, and that developers should simply use `spawn` instead and let the library decide whether it should keep the thread in the async pool.

If `task::spawn` is the recommended way to spawn tasks that may block, then users will write code that depends on that, and the design decision becomes something async-std can't revert without introducing bugs in its users. This is all fine (it seems like a good design to me), but non-obvious characteristics covered by async-std's stability guarantees should be documented.

### PR DESCRIPTION
**Pull request by jimblandy**
Fixes #905.

### CODE REVIEW

**Comment by Keruspe** [comment]
Currently this is not true anymore.

I'm working on something to maybe bring it back though

**Comment by jimblandy** [comment]
> Currently this is not true anymore.

Oh! Well, hmm. As I say in #905, once you've promised this behavior, taking it back would break all users, so it's only a feature to ship if you're willing to live with it permanently. If we've had to revert it once already, I hope that doesn't mean it's tricky.

**Comment by jimblandy** [comment]
> Currently this is not true anymore.

@Keruspe Can you link to the issue?

**Comment by joshtriplett** [comment]
Since this isn't currently planned, closing this; if in the future we re-add such support, we'll need to document it as well.

**Pull request closed without merging**
