### PR TITLE
CI: set `cache` to `cargo`

### PR DESCRIPTION
**Pull request by skade**
This should improve build times.

If this build passes, rebuild to validate.

### CODE REVIEW

**Comment by kpp** [comment]
https://levans.fr/rust_travis_cache.html

**Comment by JohnTitor** [comment]
IMO: In relation to @kpp's comment, I've recently seen jobs terminated on Travis due to cache. So `cache: cargo` may take a long time in the future. It may be better to cache `$HOME/.cargo` and `$HOME/.rustup`.

**Comment by jamesmunns** [comment]
Also chiming in that I've seen Travis' (and Gitlab CI's) caching be a net-negative to Rust CI times, particularly as time goes on.

**Comment by stjepang** [comment]
Closing in favor of #168

**Pull request closed without merging**
