### PR TITLE
expose future::{Ready,Pending}

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Implements #453. Thanks!

## Screenshots
Screenshot_2019-11-05 async_std future - Rust

### CODE REVIEW

**Comment by stjepang** [comment]
If we have `Pending` and `Ready` structs, should we also have `Timeout` and `PollFn`?

**Comment by yoshuawuyts** [comment]
@stjepang possibly?

**Comment by stjepang** [comment]
Yeah, I would say so for consistency.

**Comment by taiki-e** [comment]
> If we have `Pending` and `Ready` structs, should we also have `Timeout` and `PollFn`?

Should we also expose FuturesExt combinators?

**Comment by stjepang** [comment]
@taiki-e That's a good point. If we are exposing these futures, then it would logically follow that we should probably also expose futures returned by `FutureExt` combinators. So either we expose all future types or none.

On the other hand, we could make a rule that only future *constructors* should expose futures, while future *combinators* shouldn't.

@yoshuawuyts What's the status of this PR?

**Comment by yoshuawuyts** [comment]
@stjepang happy to close it — I'm unsure at this point and just not having it seems fine.

**Pull request closed without merging**
